# Generated by Django 4.1.7 on 2023-03-14 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_foto',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
