# Generated by Django 4.1.7 on 2023-03-25 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='data_fim_real',
            field=models.DateField(blank=True, null=True),
        ),
    ]
